Bug can't be fixed because of environment setting.
2022-08-14 17:39:00.236 ERROR 89083 --- [actory_Worker-3] org.quartz.core.JobRunShell              : Job testPipeline.step2 threw an unhandled Exception:

java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.util.StringInterner
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2600) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2492) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.get(Configuration.java:981) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:1031) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1432) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369) ~[hadoop-common-2.7.3.jar!/:na]
        at usc.donghao.taskintegration.executor.job.HdfsJob.execute(HdfsJob.java:36) ~[classes!/:2.7.2]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar!/:na]

2022-08-14 17:39:00.236 ERROR 89083 --- [actory_Worker-3] org.quartz.core.ErrorLogger              : Job (testPipeline.step2 threw an exception.

org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-2.3.2.jar!/:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar!/:na]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.util.StringInterner
        at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2600) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2492) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2405) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.get(Configuration.java:981) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:1031) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1432) ~[hadoop-common-2.7.3.jar!/:na]
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369) ~[hadoop-common-2.7.3.jar!/:na]
        at usc.donghao.taskintegration.executor.job.HdfsJob.execute(HdfsJob.java:36) ~[classes!/:2.7.2]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar!/:na]
        ... 1 common frames omitted